-- MySQL Script generated by MySQL Workbench
-- mié 04 jul 2018 01:01:19 CDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema indecisodb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema indecisodb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `indecisodb` DEFAULT CHARACTER SET utf8 ;
USE `indecisodb` ;

-- -----------------------------------------------------
-- Table `indecisodb`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `indecisodb`.`persona` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `paterno` VARCHAR(50) NOT NULL,
  `materno` VARCHAR(50) NULL,
  `fecha_nacimiento` DATE NOT NULL,
  `foto` VARCHAR(210) NULL,
  `create_date` DATETIME(6) NOT NULL,
  `write_date` DATETIME(6) NOT NULL,
  `sexo` ENUM('M', 'F') NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `indecisodb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `indecisodb`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `persona_id` INT NOT NULL,
  `email` VARCHAR(120) NOT NULL,
  `password` VARCHAR(200) NOT NULL,
  `facebook_id` VARCHAR(200) NULL,
  `create_date` DATETIME(6) NOT NULL,
  `write_date` DATETIME(6) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `fk_usuario_persona_idx` (`persona_id` ASC),
  CONSTRAINT `fk_usuario_persona`
    FOREIGN KEY (`persona_id`)
    REFERENCES `indecisodb`.`persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `indecisodb`.`grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `indecisodb`.`grupo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `persona_responsable_id` INT NOT NULL,
  `create_date` DATETIME(6) NULL,
  `write_date` DATETIME(6) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_grupo_persona1_idx` (`persona_responsable_id` ASC),
  CONSTRAINT `fk_grupo_persona1`
    FOREIGN KEY (`persona_responsable_id`)
    REFERENCES `indecisodb`.`persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `indecisodb`.`evento_estatus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `indecisodb`.`evento_estatus` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(60) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `indecisodb`.`usuario_has_grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `indecisodb`.`usuario_has_grupo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` INT NOT NULL,
  `grupo_id` INT NOT NULL,
  `es_admin` TINYINT NULL,
  `activo` TINYINT NULL,
  `create_date` DATETIME(6) NULL,
  `write_date` DATETIME(6) NULL,
  PRIMARY KEY (`id`, `usuario_id`, `grupo_id`),
  INDEX `fk_usuario_has_grupo_grupo1_idx` (`grupo_id` ASC),
  INDEX `fk_usuario_has_grupo_usuario1_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_usuario_has_grupo_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `indecisodb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_grupo_grupo1`
    FOREIGN KEY (`grupo_id`)
    REFERENCES `indecisodb`.`grupo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `indecisodb`.`evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `indecisodb`.`evento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `grupo_id` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` TEXT(400) NULL,
  `lugar` VARCHAR(254) NULL,
  `geo` POINT NULL,
  `fecha_evento` DATETIME(6) NULL,
  `evento_estatus_id` INT NOT NULL,
  `persona_id` INT NOT NULL,
  INDEX `fk_evento_estatus_has_grupo_grupo1_idx` (`grupo_id` ASC),
  INDEX `fk_evento_estatus_has_grupo_evento_estatus1_idx` (`evento_estatus_id` ASC),
  PRIMARY KEY (`id`),
  INDEX `fk_evento_estatus_has_grupo_persona1_idx` (`persona_id` ASC),
  CONSTRAINT `fk_evento_estatus_has_grupo_evento_estatus1`
    FOREIGN KEY (`evento_estatus_id`)
    REFERENCES `indecisodb`.`evento_estatus` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_evento_estatus_has_grupo_grupo1`
    FOREIGN KEY (`grupo_id`)
    REFERENCES `indecisodb`.`grupo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_evento_estatus_has_grupo_persona1`
    FOREIGN KEY (`persona_id`)
    REFERENCES `indecisodb`.`persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `indecisodb`.`evento_has_usuario_participante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `indecisodb`.`evento_has_usuario_participante` (
  `id` INT NULL AUTO_INCREMENT,
  `evento_id` INT NOT NULL,
  `persona_id` INT NOT NULL,
  `confirmado` TINYINT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_persona_has_evento_evento1_idx` (`evento_id` ASC),
  INDEX `fk_persona_has_evento_persona1_idx` (`persona_id` ASC),
  CONSTRAINT `fk_persona_has_evento_persona1`
    FOREIGN KEY (`persona_id`)
    REFERENCES `indecisodb`.`persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_persona_has_evento_evento1`
    FOREIGN KEY (`evento_id`)
    REFERENCES `indecisodb`.`evento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `indecisodb`.`evento_voto_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `indecisodb`.`evento_voto_usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `evento_id` INT NOT NULL,
  `persona_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_evento_has_persona_persona1_idx` (`persona_id` ASC),
  INDEX `fk_evento_has_persona_evento1_idx` (`evento_id` ASC),
  CONSTRAINT `fk_evento_has_persona_evento1`
    FOREIGN KEY (`evento_id`)
    REFERENCES `indecisodb`.`evento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_evento_has_persona_persona1`
    FOREIGN KEY (`persona_id`)
    REFERENCES `indecisodb`.`persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `indecisodb`;

DELIMITER $$
USE `indecisodb`$$
CREATE DEFINER = CURRENT_USER TRIGGER `indecisodb`.`persona_AFTER_INSERT` AFTER INSERT ON `persona` FOR EACH ROW
BEGIN
	SET NEW.created_date = NOW();
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
